### ISSUE TITLE
how?

### ISSUE THREAD

**Issue by AlfinaRahmawati** [jmharris7755/cassava-leaf-disease-ResNet50#1]
sorry sir for disturbing the time, want to ask how to convert image to csv? I have searched but nothing worked. are you willing to tell me how?

**Comment by jmharris7755** [comment]
Hello AlfinaRahmawati,

I am unsure what you mean by converting an image to a csv file, based on the code in this project. 

After training and saving the model, I loop through each image in the dataset used for this project, make a prediction on each image in the dataset using the trained model, and **only** write the filename and prediction value/label to a csv file. 

This process can be found in the block between saving the model, and making the accuracy and loss graphs. 

Unfortunately, nowhere in this project is an image itself converted to a csv file. I hope this clears up any questions about the code in the project.

**Comment by AlfinaRahmawati** [comment]
thank you sir
